image:
  name: docker/compose:1.23.2 # update tag to whatever version you want to use.
  entrypoint: ["/bin/sh", "-c"]

# Cache downloaded dependencies and plugins between builds.
# Not strictly necessary, but speeds up the builds.
cache:
  key: "$CI_JOB_NAME"
  paths:
    # Must be within the repository under test hence we can't use the
    # default ~/.m2
    - .m2/repository
variables:
  # Use the cached directory above.
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  
# Executed before each job



# Official docker compose image.


services:
  - docker:dind

before_script:
  - . config/maven/setup-proxy-settings.sh

build:
  stage: build
  script:
    - "cd serveur"
    - "mvn clean install -DskipTests"

stages:
  - build
  - cp
  - buildimage

buildimage:
  stage: build
  script:
    - docker build -t "serveur/metier-base/Dockerfile"
    - docker build -t "serveur/tp3/Dockerfile"
    - docker build -t "serveur/reservation-service/Dockerfile"
    - docker build -t "serveur/jwt-auth-service/Dockerfile"
    - docker build -t "serveur/banque/Dockerfile"
    - docker build -t "serveur/rabbit-mq/Dockerfile"

# Juste pour montrer un exemple de debug
dire_bonjour:
  variables:
    CI_DEBUG_TRACE: "true"
  stage: build
  script:
    - echo bonjour

# compile:
#   stage: build
  # script: "cd serveur"
 #  script: "mvn clean install -DskipTests"
  
cp:
  stage: cp
  script:
    - "cd serveur"
    - "cp metier-base/MonCinema/*.json ../../tp3/target/"
    - "cd .."

#  compose:
 #  stage: compose
#   script: "docker-compose build --no-cache"
  
# unittests:
#   stage: test
#   script: "mvn test"

# analyse:
#   variables:
#     SONAR_PROJ_KEY: "$CI_PROJECT_NAMESPACE-$CI_PROJECT_NAME:$CI_COMMIT_REF_SLUG"
 #  stage: analyse
 #  script: "mvn checkstyle:checkstyle"
