image: maven:3-jdk-8
cache:
  key: "$CI_JOB_NAME"
  paths:
    # Must be within the repository under test hence we can't use the
    # default ~/.m2
    - .m2/repository
variables:
  # Use the cached directory above.
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  
# Executed before each job
before_script:
  - . config/maven/setup-proxy-settings.sh


build:
  stage: build
  variables:
  # Use the cached directory above.
    MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  script:
    - cd serveur
    - mvn clean install -DskipTests
    - cp metier-base/MonCinema/*.json tp3/target/
    - cd ..

stages:
  - build
  - docker

docker:
  stage: docker
  image: docker:latest
  variables:
    ALL_PROXY: ""
    all_proxy: ""
    IMAGE_TAG: forge.univ-lyon1.fr:4567/p1301169/tiw1-is-2018/tiw-is-2018:latest
  services:
    - docker:dind
  before_script:
    - export DOCKER_HOST='tcp://localhost:2375'
  script:
    - apk add --update py-pip && pip install docker-compose
    - docker login -u gitlab+deploy-token-11 -p "22XLXw-JnHsUYyzgACBM" "forge.univ-lyon1.fr:4567"
    - docker build build-arg http_proxy="http://proxy.univ-lyon1.fr:3128" -f "serveur/metier-base/Dockerfile"
    - docker push "forge.univ-lyon1.fr:4567/p1301169/tiw1-is-2018/metier-base:latest"

    - docker login -u gitlab+deploy-token-11 -p "22XLXw-JnHsUYyzgACBM" "forge.univ-lyon1.fr:4567"
    - docker build build-arg http_proxy="http://proxy.univ-lyon1.fr:3128" -f "serveur/tp3/Dockerfile"
    - docker push "forge.univ-lyon1.fr:4567/p1301169/tiw1-is-2018/tp3:latest"

    - docker login -u gitlab+deploy-token-11 -p "22XLXw-JnHsUYyzgACBM" "forge.univ-lyon1.fr:4567"
    - docker build build-arg http_proxy="http://proxy.univ-lyon1.fr:3128" -f "serveur/reservation-service/Dockerfile"
    - docker push "forge.univ-lyon1.fr:4567/p1301169/tiw1-is-2018/reservation-service:latest"
   
    - docker login -u gitlab+deploy-token-11 -p "22XLXw-JnHsUYyzgACBM" "forge.univ-lyon1.fr:4567"
    - docker build build-arg http_proxy="http://proxy.univ-lyon1.fr:3128" -f "serveur/jwt-auth-service/Dockerfile"
    - docker push "forge.univ-lyon1.fr:4567/p1301169/tiw1-is-2018/jwt-auth-service:latest"

    - docker login -u gitlab+deploy-token-11 -p "22XLXw-JnHsUYyzgACBM" "forge.univ-lyon1.fr:4567"
    - docker build build-arg http_proxy="http://proxy.univ-lyon1.fr:3128" -f "serveur/banque/Dockerfile"
    - docker push "forge.univ-lyon1.fr:4567/p1301169/tiw1-is-2018/banque:latest"
   
    - docker login -u gitlab+deploy-token-11 -p "22XLXw-JnHsUYyzgACBM" "forge.univ-lyon1.fr:4567"
    - docker build build-arg http_proxy="http://proxy.univ-lyon1.fr:3128" -f "serveur/rabbit-mq/Dockerfile"
    - docker push "forge.univ-lyon1.fr:4567/p1301169/tiw1-is-2018/rabbit-mq:latest"

     # - docker-compose build
# Juste pour montrer un exemple de debug
dire_bonjour:
  variables:
    CI_DEBUG_TRACE: "true"
  stage: build
  script:
    - echo bonjour

# compile:
#   stage: build
  # script: "cd serveur"
 #  script: "mvn clean install -DskipTests"
  


#  compose:
 #  stage: compose
#   script: "docker-compose build --no-cache"
  
# unittests:
#   stage: test
#   script: "mvn test"

# analyse:
#   variables:
#     SONAR_PROJ_KEY: "$CI_PROJECT_NAMESPACE-$CI_PROJECT_NAME:$CI_COMMIT_REF_SLUG"
 #  stage: analyse
 #  script: "mvn checkstyle:checkstyle"
