version: '3'
services:
  metier-base:
    build: ./serveur/metier-base

  tp3:
    build: ./serveur/tp3
    ports:
      - "8080:8080"
    depends_on:
      - metier-base

  mypostgres:
    restart: always
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - backend

  reservations:
    build: ./serveur/reservation-service
    ports:
      - "8091:8091"
    depends_on:
      - mypostgres
    links:
      - "mypostgres:mypostgres"
    networks:
      - backend

  jwt:
    build: ./serveur/jwt-auth-service
    ports:
      - "8081:8081"
      
  frontend:
    build: ./client/cinema
    ports:
      - "8085:8085"
    environment:
      - NGINX_HTTP_PORT_NUMBER=8085
 # nginx-proxy:
 #   image: jwilder/nginx-proxy
 #   ports:
 #     - "80:80"
 #   volumes:
 #     - /var/run/docker.sock:/tmp/docker.sock:ro

networks: 
  backend:
    driver: bridge

volumes:
  data: {}
  metier:    
