version: '3'
services:
  metier-base:
    build: ./serveur/metier-base

  tp3:
    build: ./serveur/tp3
    ports:
      - "8080:8080"
    depends_on:
      - metier-base

  mypostgres:
    restart: always
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - backend

  reservations:
    build: ./serveur/reservation-service
    ports:
      - "8091:8091"
    depends_on:
      - mypostgres
    links:
      - "mypostgres:mypostgres"
    networks:
      - backend

  jwt:
    build: ./serveur/jwt-auth-service
    ports:
      - "8081:8081"
      
  angular:
    hostname: localhost
    container_name: angular-container
    build: ./client/cinema
    ports:
      - "80:80"
  
  nginx:
    # build: ./nginx
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always

networks: 
  backend:
    driver: bridge

volumes:
  data: {}
  metier:    
