version: '3'
services:
  tp3:
    build: ./tp3
    ports:
      - "8080:8080"
    volumes:
      - backend

  mypostgres:
    restart: always
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - backend

  reservations:
    build: ./reservation-service
    ports:
      - "8081:8081"
    depends_on:
      - mypostgres
    links:
      - "mypostgres:mypostgres"
    networks:
      - backend

  jwt:
    build: ./jwt-auth-service
    ports:
      - "8082:8082"
    networks:
      - backend
      
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  whoami:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=whoami.local

networks: 
  backend:
    driver: bridge

volumes:
  data: {}    